version: "3"
services:
  server:
    build: .
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
      - "${SERVER_HTTPS_PORT}:${SERVER_HTTPS_PORT}"
    environment:
      - SERVER_PORT=$SERVER_PORT
      - SERVER_HTTPS_PORT=$SERVER_HTTPS_PORT
      - DATABASE_CONNECTION_STRING=$DATABASE_CONNECTION_STRING
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - SSL_ALIAS=$SSL_ALIAS
      - SSL_PASSWORD=$SSL_PASSWORD
      - RATING_DELAY=$RATING_DELAY
    depends_on:
      - db
    networks:
      - db_network
    restart: always

  db:
    image: ${POSTGRES_IMAGE}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    environment:
      POSTGRES_DB: "pansionApp"
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - ./db-data:/var/lib/postgresql/data
#      - ./sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - db_network
    restart: always

networks:
  db_network:
    driver: bridge
