name: Build & Ship

on:
  push:
    branches:
      - main # 在 main 分支发生 push 事件时触发工作流

jobs:
  desktop-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟

    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4

      # Step 2: 下载并配置 JBR (JetBrains Runtime)
      - name: Download JetBrains Runtime (JBR)
        run: |
          mkdir jbr
          curl -L -o jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-linux-x64-b1312.2.tar.gz
          tar -xzf jbr.tar.gz -C jbr --strip-components=1
        env:
          JBR_HOME: ${{ github.workspace }}/jbr
          
      # Step 3：打印
      - name: Print
        run: |
          "jbr目录下 ：  $(ls -a jbr)"
          "当前目录：$(pwd)"
          
      # Step 4: 配置 Java 环境变量
      - name: Configure Java Environment Variables
        run: |
          echo "JAVA_HOME=${{ github.workspace }}/jbr" >> $GITHUB_ENV
          echo "PATH=${{ github.workspace }}/jbr/bin:$PATH" >> $GITHUB_ENV

      # Step 5: 构建EXE
      - name: Build exe app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:packageExe

      # Step 6：打印
      - name: Print
        run: |
          "项目结构如下 ：  $(ls -a)"
          "当前目录：$(pwd)"
          
