name: Build & Ship

on:
  push:
    branches:
      - main # 在 main 分支发生 push 事件时触发工作流

jobs:
  desktop-build:
    runs-on: ubuntu-latest
    timeout-minutes: 45 # 设置超时时间为 45 分钟

    steps:
      # Step 1: 检出代码
      - uses: actions/checkout@v4

      # Step 2: 下载并配置 JBR (JetBrains Runtime)
      - name: Download JetBrains Runtime (JBR)
        run: |
          mkdir jbr
          curl -L -o jbr.tar.gz https://cache-redirector.jetbrains.com/intellij-jbr/jbrsdk_jcef-17.0.11-linux-x64-b1312.2.tar.gz
          tar -xzf jbr.tar.gz -C jbr --strip-components=1
        env:
          JBR_HOME: ${{ github.workspace }}/jbr
          
      # Step 3：打印
      - name: Print
        run: |
          echo "jbr目录下 ：  $(ls -a jbr)"
          echo "当前目录：$(pwd)"
          
      # Step 4: 配置 Java 环境变量
      - name: Configure Java Environment Variables
        run: |
          echo "JAVA_HOME=${{ github.workspace }}/jbr" >> $GITHUB_ENV
          echo "PATH=${{ github.workspace }}/jbr/bin:$PATH" >> $GITHUB_ENV

      # Step 5: 构建EXE
      - name: Build exe app
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 20
          max_attempts: 2
          command: ./gradlew :composeApp:packageExe

      # Step 6：打印
      - name: Print
        run: |
          echo "项目结构如下 ：  $(ls -a)"
          echo "当前目录：$(pwd)"
          echo "文件路径1：$(ls composeApp/build/)"
          echo "文件路径2：$(ls composeApp/build/compose)"
          echo "文件路径遍历：$(ls -R composeApp/build/compose)"
          echo "文件路径3：$(ls composeApp/build/compose/binaries)"
          echo "文件路径4：$(ls composeApp/build/compose/binaries/main)"
          echo "文件路径5：$(ls composeApp/build/compose/binaries/main/exe/)"

      # Step 7：Upload Relase
      - name: Tag and Release
        uses: dothq/tag-and-release-and-upload@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
          # Use the version from the previous step
          version: output
          
          assets: '[ "composeApp/build/compose/binaries/main/exe/*.exe" ]'
          overwrite: true  
          
